# Generated by Django 5.2.5 on 2026-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academyprofile_playerprofile_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='region',
            field=models.CharField(default='Kampala', max_length=100),
            preserve_default=False,
        ),
    ]
