# Generated by Django 5.2.5 on 2026-02-27 14
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clubprofile_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Academies',
            },
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='club',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='club',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='player',
        ),
        migrations.RemoveField(
            model_name='videotag',
            name='video',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.academy')),
            ],
        ),
        migrations.DeleteModel(
            name='AcademyProfile',
        ),
        migrations.DeleteModel(
            name='ClubProfile',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoTag',
        ),
    ]
